### ISSUE TITLE
bout detection using the tail angle (not the video) 

### ISSUE THREAD

**Issue by mcarbotano** [oliviermirat/ZebraZoom#1]
When using the GUI I found it difficult the set the right parameters to get a good bout detection in a tail free condition. It seems the code is looking for changes in the frame characteristics to tell if there is a movement. 
I found this not optimal since many times the experiments are done under a 2P microscope, or similar, and the video will have a moving bright line form the scanning laser on the head of the animal. This could be avoided using betters filters but many people use this to proper synchronize all the stimuli and recordings. 
Would it be possible to have and option in the GUI were you choose that the bout detection is done using the tail angle tracked? or setting window to restrict where the program will be looking for the changes (or exclude and area of the video)?

Thanks!

**Comment by oliviermirat** [comment]
I just adjusted the code a little bit: it now looks for pixel changes between subsequent frames only in a restricted region of interest centered around the tail, which I think should solve this issue?
I wouldn't recommend using a threshold on the tail angle to detect bouts as I've seen it lead to less accurate bout detection than by using the pixel change method. But to try out that bout detection through tail angle changes, you can set, in the configuration files:
"thresForDetectMovementWithRawVideo" to 0, and then put "thresAngleBoutDetect" to a threshold of your choice (in radians).
