### ISSUE TITLE
better visualisation of ZZ output video

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#10]
Hi Olivier,

I recently recorded videos where the light intensity is much lower but the contrast between tail and background is still very good. 
Using zebrazoom 1.28.16, head-embedded larvae tracking.

**problem:** I don't see really much what's going on in the video with the default contrast, so when I want to check the tracking using GUI "visualise ZZ output" "View video for well 0", I don't see the tail. And I would rather not go to each video and change the contrast manually before running it with ZZ.
Images provides example frames from the output video from ZZ:
raw frame
![211006_F2_run4_example](https://user-images.githubusercontent.com/50573983/136788927-3fc87033-4532-408a-98d0-70feca994d91.png)
inverted LUT
![211006_F2_run4_example_invert_LUT](https://user-images.githubusercontent.com/50573983/136788944-5b87a056-9030-471d-aa3a-e097d6b7c4ee.png)
inverted LUT, manually enhanced contrast
![211006_F2_run4_example_invert_LUT_enhanced](https://user-images.githubusercontent.com/50573983/136788952-0ff66d08-3c18-4a28-84c0-028b27811b94.png)

We already discussed this a while back as an issue to click on tail tip and tail start; and you enhanced the contrast of the video specifically for the selection of the tail tip and tail start, but only in the function "Run ZZ on a folder", not on "Run ZZ on a video".

**proposed solution:** Would it be possible to apply to the main output video:
1) when we have a white zebrafish on black background, Invert the LUT (parameter already in config file): it's much easier to distinguish on a screen.
2) enhance the contrast automatically to fill the histogram (set min to the lowest value and max to 99% or something - what you're doing in "Run ZZ on a folder" works really nicely).
(they could be options to add to the config file if you want to leave the user the option to apply this or not).

It would make my life much simpler to check efficiency of tracking in all conditions of illuminations (irght now I need to load the output video in ImageJ and check manually all bouts).

Please let me know if my issue is not clear.

Thanks !

**Comment by oliviermirat** [comment]
Hi Mathilde,

I think this issue is already solved. If you add the parameter:
"outputValidationVideoContrastImprovement": 1
inside your configuration file, you should get something very similar to what you're asking for. Can you please check that this solves the issue?

About the contrast enhancement specifically for the selection of the tail tip and tail start: I just upgraded the code (1.28.20 now) and now this contrast enhancement should now also be happening for the "Run ZZ on a video" option.

Please let me know if this works and if you have any other questions.

**Comment by mathildelpx** [comment]
Hi Olivier,

Thanks for the response, I had forgotten about that, sorry !
It works really nicely now.

I actually got an error when I updated to version 1.28.20, which I think is completely linked to the update:

Process Process-1:
Traceback (most recent call last):
  File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/zebrazoom/mainZZ.py", line 40, in getParametersForWell
    trackingData = tracking(videoPath,background,wellNumber,wellPositions,hyperparameters, videoName, dlModel)
  File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/zebrazoom/code/trackingFolder/tracking.py", line 87, in tracking
    [frame, thresh1] = headEmbededFrameBackExtract(videoPath, background, hyperparameters, firstFrame)
  File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/zebrazoom/code/getImage/headEmbededFrameBackExtract.py", line 10, in headEmbededFrameBackExtract
    cap = zzVideoReading.VideoCapture(videoPath)
NameError: name 'zzVideoReading' is not defined

**Comment by mathildelpx** [comment]
sorry - missing info:

running ZZ tracking on one video

config:
{"extractAdvanceZebraParameters": 1, "headEmbeded": 1, "invertBlackWhiteOnImages": 0, "outputValidationVideoContrastImprovement": 1, "extractBackWhiteBackground": 0, "automaticallySetSomeOfTheHeadEmbededHyperparameters": 1, "findHeadPositionByUserInput": 1, "detectBoutMinDist": -1, "detectBoutMinNbFrames": 5, "detectBoutMinAngleDiff": 0.01, "minDiffBetweenSubsequentBendAmp": 0.01, "windowForLocalBendMinMaxFind": 3, "fillGapFrameNb": 5, "tailAngleMedianFilter": 3, "nbWells": 1, "nbList": 20, "headingCalculationMethod": "calculatedWithMedianTailTip", "exitAfterBackgroundExtraction": 0, "headEmbededRemoveBack": 0, "debugExtractBack": 0, "onlyTrackThisOneWell": -1, "reloadBackground": 0, "noBoutsDetection": 0, "trackTail": 1, "adjustDetectMovWithRawVideo": 0, "reloadWellPositions": 0, "thresForDetectMovementWithRawVideo": 4, "frameGapComparision": 5, "halfDiameterRoiBoutDetect": 476.111801242236, "minNbPixelForDetectMovementWithRawVideo": 4, "adjustHeadEmbededTracking": 0, "headEmbededAutoSet_BackgroundExtractionOption": 1, "overwriteFirstStepValue": 0, "overwriteLastStepValue": 0, "headEmbededParamTailDescentPixThreshStopOverwrite": -2, "authorizedRelativeLengthTailEnd": 0.8500000000000001, "overwriteHeadEmbededParamGaussianBlur": 0, "perBoutOutput": 1, "perBoutOutputVideoStartStopFrameMargin": 50, "perBoutOutputYaxis": [-100, 100], "smoothTailHeadEmbeded": 50, "nbTailPoints": 20, "curvatureMedianFilterSmoothingWindow": 3, "calculateAllTailAngles": 1}

**Comment by oliviermirat** [comment]
Thank you for the useful feedback.

I just updated the code (1.28.21 now): it should work now.

Please let me know if you see any other issues.

**Comment by mathildelpx** [comment]
perfect, all good with the new version.

Thanks Olivier !
