### ISSUE TITLE
 UnboundLocalError: local variable 'tailLength' referenced before assignment

### ISSUE THREAD

**Issue by SDu90** [oliviermirat/ZebraZoom#119]
I am using Zebrazoom for the first time. While trying to create initial configuration files using Head and Tail tracking, I am getting this error message.

**Comment by oliviermirat** [comment]
Hello, could you please provide the full error message that's being printed in the console?
We should be able to troubleshoot more easily if we can get that full error message / traceback.

**Comment by SDu90** [comment]
Hello Olivier,

Thanks a lot for your email. Here it is:


/Applications/ZebraZoom-macOS/ZebraZoomApp ; exit;

***@***.*** ~ % /Applications/ZebraZoom-macOS/ZebraZoomApp ; exit;

The data produced by ZebraZoom can be found in the folder: /Applications/ZebraZoom-macOS/ZebraZoom/zebrazoom/ZZoutput

2024-04-10 15:10:55.355 ZebraZoomApp[2773:59498] +[CATransaction synchronize] called within transaction

2024-04-10 15:10:55.458 ZebraZoomApp[2773:59498] +[CATransaction synchronize] called within transaction

command line hyperparameter change: outputFolder /var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpweytls_k

start find wells

exitAfterWellsDetection

initialConfigFile: {'extractAdvanceZebraParameters': 1, 'headEmbeded': 0, 'noWellDetection': 1, 'nbWells': 1, 'firstFrame': 4102, 'firstFrameForBackExtract': 4102, 'lastFrame': 4558, 'lastFrameForBackExtract': 4558, 'noBoutsDetection': 1, 'noChecksForBoutSelectionInExtractParams': 1, 'trackingPointSizeDisplay': 4, 'validationVideoPlotHeading': 0, 'nbAnimalsPerWell': 1, 'outputFolder': '/var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpweytls_k'}

Background Extracted

Tracking done for well 0

minPixelDiffForBackExtract: 3 ; tailTipDistError: 987.4168319407969

Tracking done for well 0

minPixelDiffForBackExtract: 4 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 5 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 6 ; tailTipDistError: 987.4168319407969

Tracking done for well 0

minPixelDiffForBackExtract: 7 ; tailTipDistError: 987.4168319407969

Tracking done for well 0

minPixelDiffForBackExtract: 8 ; tailTipDistError: 987.4168319407969

Tracking done for well 0

minPixelDiffForBackExtract: 9 ; tailTipDistError: 835.0239517522836

Tracking done for well 0

minPixelDiffForBackExtract: 10 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 11 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 12 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 13 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 14 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 15 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 16 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 17 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 18 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 19 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 20 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 21 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 22 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 23 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 24 ; tailTipDistError: 987.1544965201749

Tracking done for well 0

minPixelDiffForBackExtract: 3 ; tailTipDistError: 968.0082644275305

Tracking done for well 0

minPixelDiffForBackExtract: 4 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 5 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 6 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 7 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 8 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 9 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 10 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 11 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 12 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 13 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 14 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 15 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 16 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 17 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 18 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 19 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 20 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 21 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 22 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 23 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 24 ; tailTipDistError: 796.1362948641395

Tracking done for well 0

minPixelDiffForBackExtract: 3 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 4 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 5 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 6 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 7 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 8 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 9 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 10 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 11 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 12 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 13 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 14 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 15 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 16 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 17 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 18 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 19 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 20 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 21 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 22 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 23 ; tailTipDistError: 967.9101197941883

Tracking done for well 0

minPixelDiffForBackExtract: 24 ; tailTipDistError: 967.9101197941883

tailLengthManualOptions: [68.65857557508748, 73.78346698278686, 72.42237223399962]

maxTailLengthManual: 73.78346698278686

bestMinPixelDiffForBackExtractOptions: []

tailLengthOptions: []

bodyContourAreaOptions: []

NEED TO START OVER: bodyContourArea

NEED TO START OVER


Thanks,

Suchetana B. Dutta
PostDoctoral Research Associate
Becker Lab

Neural Development and Regeneration
Technische Universität Dresden
Center for Molecular and Cellular Bioengineering (CMCB)
Centre for Regenerative Therapies (CRTD)
Fetscherstraße 105
01307 Dresden
Germany
Email: ***@***.******@***.***>
Webpage: https://tudresden.de/cmcb/crtd/forschungsgruppen/crtd-forschungsgruppen/becker



From: Olivier Mirat ***@***.***>
Reply to: oliviermirat/ZebraZoom ***@***.***>
Date: Wednesday, 10. April 2024 at 15:31
To: oliviermirat/ZebraZoom ***@***.***>
Cc: "Dutta, Suchetana Bias" ***@***.***>, Author ***@***.***>
Subject: Re: [oliviermirat/ZebraZoom] UnboundLocalError: local variable 'tailLength' referenced before assignment (Issue #119)


Hello, could you please provide the full error message that's being printed in the console?
We should be able to troubleshoot more easily if we can get that full error message / traceback.

**Comment by oliviermirat** [comment]
It looks like the method to automatically find good config file parameters won't work in the case of your video.
Could you please send your video (or a portion of it if it's too heavy (more than one 1GB)) to this email address: info@zebrazoom.org ? That way I will be able to look more precisely at what's happening.
If you need to extract a sub-video out of your original video you can use the troubleshoot button at the very bottom of the welcome page of ZebraZoom's GUI (please try to select a portion of the video where the animal is moving)

**Comment by SDu90** [comment]
Hello Olivier,

Due to email size regulation of the university, I have sent you the video from my gmail ***@***.******@***.***>). Hope it works.

Thanks,

Suchetana B. Dutta
PostDoctoral Research Associate
Becker Lab

Neural Development and Regeneration
Technische Universität Dresden
Center for Molecular and Cellular Bioengineering (CMCB)
Centre for Regenerative Therapies (CRTD)
Fetscherstraße 105
01307 Dresden
Germany
Email: ***@***.******@***.***>
Webpage: https://tudresden.de/cmcb/crtd/forschungsgruppen/crtd-forschungsgruppen/becker



From: Olivier Mirat ***@***.***>
Reply to: oliviermirat/ZebraZoom ***@***.***>
Date: Wednesday, 10. April 2024 at 15:43
To: oliviermirat/ZebraZoom ***@***.***>
Cc: "Dutta, Suchetana Bias" ***@***.***>, Author ***@***.***>
Subject: Re: [oliviermirat/ZebraZoom] UnboundLocalError: local variable 'tailLength' referenced before assignment (Issue #119)


It looks like the method to automatically find good config file parameters won't work in the case of your video.
Could you please send your video (or a portion of it if it's too heavy (more than one 1GB)) to this email address: ***@***.******@***.***> ? That way I will be able to look more precisely at what's happening.
If you need to extract a sub-video out of your original video you can use the troubleshoot button at the very bottom of the welcome page of ZebraZoom's GUI (please try to select a portion of the video where the animal is moving)
