### ISSUE TITLE
Failure to track zebrafish larvae

### ISSUE THREAD

**Issue by SDu90** [oliviermirat/ZebraZoom#127]
Hello,

Here is the error message that I am receiving while trying to track zebrafish larvae using Zebrazoom:
**An error has ocurred: cv2.error: OpenCV(4.9.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/drawing.cpp:1832: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'.**

For further details, I am also pasting the details from the logbook:

Last login: Mon Sep 23 09:44:34 on ttys000
/Applications/ZebraZoom-macOS/ZebraZoomApp ; exit;                              
suchetanadutta@crtd-becker-mac05 ~ % /Applications/ZebraZoom-macOS/ZebraZoomApp ; exit;
The data produced by ZebraZoom can be found in the folder: /Applications/ZebraZoom-macOS/ZebraZoom/zebrazoom/ZZoutput
command line hyperparameter change: outputFolder /var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpylzfbe5w
start find wells
exitAfterWellsDetection
initialConfigFile: {'extractAdvanceZebraParameters': 1, 'headEmbeded': 0, 'groupOfMultipleSameSizeAndShapeEquallySpacedWells': 1, 'nbWells': 1, 'nbAnimalsPerWell': 2, 'nbRowsOfWells': 1, 'nbWellsPerRows': 1, 'noBoutsDetection': 1, 'noChecksForBoutSelectionInExtractParams': 1, 'trackingPointSizeDisplay': 4, 'validationVideoPlotHeading': 0, 'multipleHeadTrackingIterativelyRelaxAreaCriteria': 1, 'outputFolder': '/var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpylzfbe5w'}
Background Extracted
Tracking done for well 0
minPixelDiffForBackExtract: 3 ; tailTipDistError: 5.830951894845301
Tracking done for well 0
minPixelDiffForBackExtract: 4 ; tailTipDistError: 5.830951894845301
Tracking done for well 0
minPixelDiffForBackExtract: 5 ; tailTipDistError: 5.830951894845301
Tracking done for well 0
minPixelDiffForBackExtract: 6 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 7 ; tailTipDistError: 5.0
Tracking done for well 0
minPixelDiffForBackExtract: 8 ; tailTipDistError: 4.47213595499958
Tracking done for well 0
minPixelDiffForBackExtract: 9 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 10 ; tailTipDistError: 1.0
Tracking done for well 0
minPixelDiffForBackExtract: 11 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 12 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 13 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 14 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 15 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 16 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 17 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 18 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 19 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 20 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 21 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 22 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 23 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 24 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 3 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 4 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 5 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 6 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 7 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 8 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 9 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 10 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 11 ; tailTipDistError: 5.0990195135927845
Tracking done for well 0
minPixelDiffForBackExtract: 12 ; tailTipDistError: 5.0990195135927845
Tracking done for well 0
minPixelDiffForBackExtract: 13 ; tailTipDistError: 6.082762530298219
Tracking done for well 0
minPixelDiffForBackExtract: 14 ; tailTipDistError: 6.082762530298219
Tracking done for well 0
minPixelDiffForBackExtract: 15 ; tailTipDistError: 6.324555320336759
Tracking done for well 0
minPixelDiffForBackExtract: 16 ; tailTipDistError: 11.40175425099138
Tracking done for well 0
minPixelDiffForBackExtract: 17 ; tailTipDistError: 18.439088914585774
Tracking done for well 0
minPixelDiffForBackExtract: 18 ; tailTipDistError: 18.973665961010276
Tracking done for well 0
minPixelDiffForBackExtract: 19 ; tailTipDistError: 19.924858845171276
Tracking done for well 0
minPixelDiffForBackExtract: 20 ; tailTipDistError: 19.6468827043885
Tracking done for well 0
minPixelDiffForBackExtract: 21 ; tailTipDistError: 20.615528128088304
Tracking done for well 0
minPixelDiffForBackExtract: 22 ; tailTipDistError: 23.53720459187964
Tracking done for well 0
minPixelDiffForBackExtract: 23 ; tailTipDistError: 30.463092423455635
Tracking done for well 0
minPixelDiffForBackExtract: 24 ; tailTipDistError: 30.463092423455635
Tracking done for well 0
minPixelDiffForBackExtract: 3 ; tailTipDistError: 38.28837943815329
Tracking done for well 0
minPixelDiffForBackExtract: 4 ; tailTipDistError: 37.589892258425
Tracking done for well 0
minPixelDiffForBackExtract: 5 ; tailTipDistError: 38.27531841800928
Tracking done for well 0
minPixelDiffForBackExtract: 6 ; tailTipDistError: 38.948684188300895
Tracking done for well 0
minPixelDiffForBackExtract: 7 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 8 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 9 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 10 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 11 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 12 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 13 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 14 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 15 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 16 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 17 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 18 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 19 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 20 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 21 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 22 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 23 ; tailTipDistError: 3.1622776601683795
Tracking done for well 0
minPixelDiffForBackExtract: 24 ; tailTipDistError: 4.123105625617661
Tracking done for well 0
minPixelDiffForBackExtract: 3 ; tailTipDistError: 50.60632371551998
Tracking done for well 0
minPixelDiffForBackExtract: 4 ; tailTipDistError: 38.2099463490856
Tracking done for well 0
minPixelDiffForBackExtract: 5 ; tailTipDistError: 38.2099463490856
Tracking done for well 0
minPixelDiffForBackExtract: 6 ; tailTipDistError: 4.47213595499958
Tracking done for well 0
minPixelDiffForBackExtract: 7 ; tailTipDistError: 4.47213595499958
Tracking done for well 0
minPixelDiffForBackExtract: 8 ; tailTipDistError: 1.0
Tracking done for well 0
minPixelDiffForBackExtract: 9 ; tailTipDistError: 1.0
Tracking done for well 0
minPixelDiffForBackExtract: 10 ; tailTipDistError: 1.0
Tracking done for well 0
minPixelDiffForBackExtract: 11 ; tailTipDistError: 1.0
Tracking done for well 0
minPixelDiffForBackExtract: 12 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 13 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 14 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 15 ; tailTipDistError: 1.4142135623730951
Tracking done for well 0
minPixelDiffForBackExtract: 16 ; tailTipDistError: 2.23606797749979
Tracking done for well 0
minPixelDiffForBackExtract: 17 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 18 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 19 ; tailTipDistError: 2.0
Tracking done for well 0
minPixelDiffForBackExtract: 20 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 21 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 22 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 23 ; tailTipDistError: 3.0
Tracking done for well 0
minPixelDiffForBackExtract: 24 ; tailTipDistError: 3.0
tailLengthManualOptions: [69.05070600652827, 71.30918594402827, 71.386273190299, 69.42621983083913]
maxTailLengthManual: 71.386273190299
bestMinPixelDiffForBackExtractOptions: [10, 5, 7, 8]
tailLengthOptions: [69.6511204041619, 70.50415164232302, 72.11162835515054, 70.71388015012714]
bodyContourAreaOptions: [662.5, 952.0, 0.0, 0.0]
headContourAreaOptions: [752.0, 822.0]
Intermediary config file: {'extractAdvanceZebraParameters': 1, 'headEmbeded': 0, 'nbWells': 1, 'noBoutsDetection': 1, 'noChecksForBoutSelectionInExtractParams': 1, 'trackingPointSizeDisplay': 0, 'validationVideoPlotHeading': 1, 'nbAnimalsPerWell': 2, 'forceBlobMethodForHeadTracking': 1, 'multipleHeadTrackingIterativelyRelaxAreaCriteria': 1, 'erodeIter': 0, 'minArea': 0, 'maxArea': 0.0, 'minAreaBody': 0, 'maxAreaBody': 0.0, 'headSize': 36, 'minTailSize': 7.211162835515054, 'maxTailSize': 144.2232567103011, 'paramGaussianBlur': 25, 'extractBackWhiteBackground': 1, 'dilateIter': 0, 'thresholdForBlobImg': 254, 'findContourPrecision': 'CHAIN_APPROX_NONE', 'midlineIsInBlobTrackingOptimization': 0, 'checkAllContourForTailExtremityDetect': 1, 'recalculateForegroundImageBasedOnBodyArea': 0, 'headingCalculationMethod': 'simplyFromPreviousCalculations', 'detectMouthInsteadOfHeadTwoSides': 1, 'findCenterOfAnimalByIterativelyDilating': 1, 'minPixelDiffForBackExtract': 7, 'adjustMinPixelDiffForBackExtract_nbBlackPixelsMax': 0.0, 'nbRowsOfWells': 1, 'nbWellsPerRows': 1, 'groupOfMultipleSameSizeAndShapeEquallySpacedWells': 1}
final Config File {'extractAdvanceZebraParameters': 1, 'headEmbeded': 0, 'nbWells': 1, 'noBoutsDetection': 1, 'noChecksForBoutSelectionInExtractParams': 1, 'trackingPointSizeDisplay': 0, 'validationVideoPlotHeading': 1, 'nbAnimalsPerWell': 2, 'forceBlobMethodForHeadTracking': 1, 'multipleHeadTrackingIterativelyRelaxAreaCriteria': 1, 'erodeIter': 0, 'minArea': 0, 'maxArea': 0.0, 'minAreaBody': 0, 'maxAreaBody': 0.0, 'headSize': 36, 'minTailSize': 7.211162835515054, 'maxTailSize': 144.2232567103011, 'paramGaussianBlur': 25, 'extractBackWhiteBackground': 1, 'dilateIter': 0, 'thresholdForBlobImg': 254, 'findContourPrecision': 'CHAIN_APPROX_NONE', 'midlineIsInBlobTrackingOptimization': 0, 'checkAllContourForTailExtremityDetect': 1, 'recalculateForegroundImageBasedOnBodyArea': 1, 'headingCalculationMethod': 'simplyFromPreviousCalculations', 'detectMouthInsteadOfHeadTwoSides': 1, 'findCenterOfAnimalByIterativelyDilating': 1, 'minPixelDiffForBackExtract': 7, 'adjustMinPixelDiffForBackExtract_nbBlackPixelsMax': 0.0, 'nbRowsOfWells': 1, 'nbWellsPerRows': 1, 'groupOfMultipleSameSizeAndShapeEquallySpacedWells': 1, 'storeH5': 1, 'createValidationVideo': 0}
command line hyperparameter change: firstFrame 1
command line hyperparameter change: lastFrame 501
command line hyperparameter change: freqAlgoPosFollow 100
command line hyperparameter change: popUpAlgoFollow 1
command line hyperparameter change: outputFolder /var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpylzfbe5w
command line hyperparameter change: backgroundExtractionForceUseAllVideoFrames 1
start find wells
start get background
Background Extracted
Tracking: frame: 100
Tracking at frame 100
Tracking: frame: 200
Tracking at frame 200
Tracking: frame: 300
Tracking at frame 300
Tracking: frame: 400
Tracking at frame 400
Tracking: frame: 500
Tracking at frame 500
Extract Param Begin: wellNumber: 0  ; frame: 0
Extract Param Begin: wellNumber: 0  ; frame: 100
Extract Param Begin: wellNumber: 0  ; frame: 200
Extract Param Begin: wellNumber: 0  ; frame: 300
Extract Param Begin: wellNumber: 0  ; frame: 400
Extract Param Begin: wellNumber: 0  ; frame: 500
Extract Param Middle: wellNumber: 0  ; frame: 500
Extract Param End1 Freq*10 : wellNumber: 0  ; frame: 0
Extract Param End2 Freq*10 : wellNumber: 0  ; frame: 0
Extract Param Begin: wellNumber: 0  ; frame: 0
Extract Param Begin: wellNumber: 0  ; frame: 100
Extract Param Begin: wellNumber: 0  ; frame: 200
Extract Param Begin: wellNumber: 0  ; frame: 300
Extract Param Begin: wellNumber: 0  ; frame: 400
Extract Param Begin: wellNumber: 0  ; frame: 500
Extract Param Middle: wellNumber: 0  ; frame: 500
Extract Param End1 Freq*10 : wellNumber: 0  ; frame: 0
Extract Param End2 Freq*10 : wellNumber: 0  ; frame: 0
Parameters extracted for well 0
Starting the creation of the super structure
Super Structure created
Creating pandas dataframe of parameters
Parameter: frameStepForDistanceCalculation: 4
Calculating and storing all parameters:
trial_id: 1-subvideo_2024_09_23-10_02_11  ; Well_ID: 0
Store results: /var/folders/n2/n4w_mr1d0x50qx9n6r_9qs3h0000gq/T/tmpylzfbe5w/1-subvideo_2024_09_23-10_02_11.h5
Traceback (most recent call last):
  File "zebrazoom/code/GUI/GUI_InitialClasses.py", line 1262, in <lambda>
  File "zebrazoom/code/GUI/GUI_InitialClasses.py", line 1608, in showValidationVideo
  File "zebrazoom/code/GUI/readValidationVideo.py", line 599, in readValidationVideo
  File "zebrazoom/code/GUI/readValidationVideo.py", line 258, in getFrame
  File "zebrazoom/code/createValidationVideo.py", line 182, in drawInfoFrame
cv2.error: OpenCV(4.9.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/drawing.cpp:1832: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

Hope this helps. Thanks :)

**Comment by oliviermirat** [comment]
Hi Suchetana,

Thank you for the feedback.

It appears like "trackingPointSizeDisplay" was set by ZebraZoom to 0 in the configuration file you created, which should not happen, the software usually prevents this from happening. However, after some investigation, I realized that there was a situation where this could happen. I've now just fixed that and released a new version of ZebraZoom which should now always prevent "trackingPointSizeDisplay" from being set to 0.

Please upgrade ZebraZoom to the latest version I just released (1.34.59), then recreate a configuration file from scratch, check that "trackingPointSizeDisplay" was set to a value strictly higher than 0, then relaunch the tracking. Using this you should now be able to visualize the video after the tracking is done.

However, when looking more carefully at the configuration file that was created by ZebraZoom, I also realized that some other parameters (such as minArea and maxArea) were also set to 0 which indicates that some other problem occurred during the configuration file creation. If you try re-creating a new configuration file as suggested above, thoseminArea and maxArea values might end up being different than 0 (as the configuration file creation pipeline has some randomness within it): if so then the tracking should work. If not then, you could potentially try creating the configuration file with another video in your dataset (if there are other videos) and see if that works. Otherwise, please send me your video (or a subvideo of it if it is very large) and I can investigate further.

Best,

Olivier

**Comment by SDu90** [comment]
Hello Olivier,

I have now updated the version and it works.

So sorry for not getting back to you after our conversation. I had to go through a knee surgery and was on sick leave for 2 months. I have just resumed work and slowly starting my projects again. I have discussed the options with Catherina and Thomas, they definitely want to pursue the lower cost option that is, hiring you as a freelancer for the required quantifications for calculating C-bend angle and also body angle while larvae do the rhythmic cyclic swim after the initial C-bend. Also, we have the problem of tracking when the larvae isn’t moving at all.

Actually, I am in the process of writing a small. Grant and hoping to get it. Then the plan is also to buy a better camera with 500fps so that we can actually do the C-bend analysis. Because the camera we have now does 70fps which is too low and I also tried with a normal phone camera which is 120fps. I can still send you some screenshots of the images that I acquire for your reference. But do you think it is better to wait for the camera or we can think about 1. troubleshooting the failure to track non moving larvae post touch 2. How to analyze the oscillating body movement after the initial C-bend.

Thanks a lot and have a nice day.

Thanks,

Suchetana B. Dutta
PostDoctoral Research Associate
Becker Lab

Neural Development and Regeneration
Technische Universität Dresden
Center for Molecular and Cellular Bioengineering (CMCB)
Centre for Regenerative Therapies (CRTD)
Fetscherstraße 105
01307 Dresden
Germany
Email: ***@***.******@***.***>
Webpage: https://tudresden.de/cmcb/crtd/forschungsgruppen/crtd-forschungsgruppen/becker



From: Olivier Mirat ***@***.***>
Reply to: oliviermirat/ZebraZoom ***@***.***>
Date: Monday, 23. September 2024 at 11:34
To: oliviermirat/ZebraZoom ***@***.***>
Cc: "Dutta, Suchetana Bias" ***@***.***>, Author ***@***.***>
Subject: Re: [oliviermirat/ZebraZoom] Failure to track zebrafish larvae (Issue #127)


Hi Suchetana,

Thank you for the feedback.

It appears like "trackingPointSizeDisplay" was set by ZebraZoom to 0 in the configuration file you created, which should not happen, the software usually prevents this from happening. However, after some investigation, I realized that there was a situation where this could happen. I've now just fixed that and released a new version of ZebraZoom which should now always prevent "trackingPointSizeDisplay" from being set to 0.

Please upgrade ZebraZoom to the latest version I just released (1.34.59), then recreate a configuration file from scratch, check that "trackingPointSizeDisplay" was set to a value strictly higher than 0, then relaunch the tracking. Using this you should now be able to visualize the video after the tracking is done.

However, when looking more carefully at the configuration file that was created by ZebraZoom, I also realized that some other parameters (such as minArea and maxArea) were also set to 0 which indicates that some other problem occurred during the configuration file creation. If you try re-creating a new configuration file as suggested above, thoseminArea and maxArea values might end up being different than 0 (as the configuration file creation pipeline has some randomness within it): if so then the tracking should work. If not then, you could potentially try creating the configuration file with another video in your dataset (if there are other videos) and see if that works. Otherwise, please send me your video (or a subvideo of it if it is very large) and I can investigate further.

Best,

Olivier
