### ISSUE TITLE
Visualise ZZ output: fix ylim on right side plot to compare easily across bouts

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#13]
Hi Olivier,

Using zebrazoom 1.30.21, 

**context**

Currently when visualising ZZ output, I use the right side plot of tail angle over time. 

**encountered issue**

My problem is that currently, the yaxis limit is auto-generated so it is not easily comparable across bouts. It really slows the process of going through the bouts and getting an idea of what kind of behavior the fish was doing. 

**Proposition**

Set ylim of this plot that would be common to all bouts. It could either be one fixed value that fits all data (-120,120) or min and max of all bouts in the visualised experiments. If you think it is a feature that not everyone would want to use, it could be set using an additional button in the "Visualise ZZ output" interface, for example "Set common ylim for all bouts".

Thanks !

**Comment by oliviermirat** [comment]
Hi Mathilde,

I think that clicking on the button "Zoom out Graph" (near the middle bottom part of the visualization page) would allow to do this?

Please let me know if that doesn't fix the issue.

**Comment by mathildelpx** [comment]
Excellent, that's exactly what I was looking for. 

Thanks!
