### ISSUE TITLE
parameter 'outputValidationVideoFps' should appear in the default json config?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [oliviermirat/ZebraZoom#14]
It seems like this parameter is meant to appear in 'defaultConfigFile.json', probably with value '-1'?  Without this, a diagnostic is printed.

**Comment by oliviermirat** [comment]
Thank you for the feedback! You are right, that parameter was missing in defaultConfigFile.json, I've corrected the error and just pushed a new version on Github and PyPi with the fix.
