### ISSUE TITLE
Avoid infinite wait loops on filesystem errors

### ISSUE THREAD

**Issue by michaelkarlcoleman** [oliviermirat/ZebraZoom#15]
There are several places where the code waits forever for an error (e.g., a missing directory or full disk) to abate.  At least in a command-line scenario, these should just error out immediately, with a helpful error message.

```
  while True:
    try:
      os.mkdir(outputFolderVideo)
      break
    except OSError as e:
      print("waiting inside except")
      time.sleep(0.1)
    else:
      print("waiting")
      time.sleep(0.1)
```

**Comment by oliviermirat** [comment]
Thank you for the feedback.
Actually, the code waits forever until the folder is successfully created then breaks out of the infinite while loop. This is needed because in some cases, the folder can't be created on the first try (I think this is because sometimes that same folder is still in the process of being deleted from a previous line of code).
There might be some better ways of implementing this though, if you have any ideas feel free to let me know :)

**Comment by michaelkarlcoleman** [comment]
The issue is that for a bogus `outputFolder`, the `os.mkdir` will always throw an `OSError`, barring some surprising external fix.  This is more important in a HPC environment, as the resources allocated to this process cannot be released for others to use.

I'm not exactly sure what scenario is being contemplated here.  For a single process with a single thread, generally this `os.mkdir` will either succeed or it won't.  (Once the `shutil.rmtree` completes, the directory will definitely be gone, unless that function has signaled an error.  There isn't some sense in which the deletion will happen at some later point, for POSIX (Linux and Mac) and almost certainly for Windows as well.)

If there are multiple threads and/or processes, the story is slightly more complex.  For threads, since the `rmtree` and `mkdir` are happening in the same thread, it should be as above.  If you had two different processes running through this code, both pointed at the same `outputFolder`, they could conceivably step on each other.  I'd be inclined to just say "don't do that".

It doesn't seem needed, but you could make these steps more atomic by renaming the existing directory (if present) to give it a temporary name (see tmpnam and friends), then do the mkdir, then rmtree the old renamed directory.

For my purposes, it would be sufficient to perhaps have a config option (`failFast`?) to cause immediate errors rather than looping.  I'm not sure this is right, as I'm not sure exactly how your code is structured, especially since some of it supports a GUI.

**Comment by oliviermirat** [comment]
Ok, thank you for the comments and insights, I may try to investigate this issue further later.
For now, I've just released a new version in which I added a new parameter, tryCreatingFolderUntilSuccess, which if set to 0 in the configuration file, won't do the infinite loop (instead it will just try one time to create the folder). I've added this for the animal tracking part of the code only (which is usually the part that's being run on HPC.
Please let me know if this isn't enough.
