### ISSUE TITLE
Infinite loop in getForegroundImageSequential

### ISSUE THREAD

**Issue by michaelkarlcoleman** [oliviermirat/ZebraZoom#16]
First timer using ZebraZoom on a set of 30 `.avi` files for a researcher (a prior coauthor of yours, and who provided the config file).  Some completed, but a significant number seem to be hung (using 100% CPU but performing no system calls).  Sending a few a SIGINT, they all get a traceback suggesting that they are trapped in this loop.

Not sure of the exact API for these OpenCV functions, but it appears that in unusual circumstances (perhaps a corrupted input file), this loop could simply run indefinitely.  In particular, one imagines that `currentFrameNum` could go negative, at which point continued failure might be guaranteed.  At an absolute minimum, perhaps the program should fail out if that happened.  It would be nice, of course, if there were some explanation (e.g., if file corruption could be detected).

https://github.com/oliviermirat/ZebraZoom/blob/61d1c3e0ff61be5a63556e277add1fbc3f67baf8/zebrazoom/code/getImage/getForegroundImageSequential.py#L25-L30

Example traceback:
```
Process Process-1:
Traceback (most recent call last):
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/site-packages/zebrazoom/mainZZ.py", line 40, in getParametersForWell
    trackingData = tracking(videoPath,background,wellNumber,wellPositions,hyperparameters, videoName, dlModel)
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/site-packages/zebrazoom/code/trackingFolder/tracking.py", line 157, in tracking
    [frame, gray, thresh1, blur, thresh2, frame2, initialCurFrame, back, xHead, yHead] = getImages(hyperparameters, cap, videoPath, i, background, wellNumber, wellPositions, 0, trackingHeadTailAllAnimals)
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/site-packages/zebrazoom/code/trackingFolder/getImages.py", line 37, in getImages
    [frame, initialCurFrame, back, xHead, yHead] = getForegroundImageSequential(cap, videoPath, background, i, wellNumber, wellPositions, hyperparameters, alreadyExtractedImage, trackingHeadTailAllAnimals)
  File "/packages/miniconda/20190102/envs/zebrazoom-20220204/lib/python3.9/site-packages/zebrazoom/code/getImage/getForegroundImageSequential.py", line 30, in getForegroundImageSequential
    ret, frame = cap.read()
KeyboardInterrupt
```

(Also, the `multiprocessing` module doesn't seem to notice that one of its processes has died, which is minorly annoying, but probably not the fault of ZebraZoom.)

**Comment by oliviermirat** [comment]
Thank you for looking into all this. 
It's strange, I've never seen it do something quite like that before.
In any case, I've just added a new parameter in the list of possible parameters in the configuration files: searchPreviousFramesIfCurrentFrameIsCorrupted
This parameter is set to 1 by default. If set to 0, it won't do any loops to look for frames: if a frame can't be read, it will just set it to the background. So setting it to 0 may help in your case.
Something else I could suggest: the parameter "lastFrame" is calculated automatically but sometimes the value calculated is slightly off, so it could be a good idea to manually fix the parameter "lastFrame" to the right value inside the configuration file instead.

**Comment by michaelkarlcoleman** [comment]
Hi Olivier,

Your co-author was able to get this running here.  I'll admit, I have no idea why she didn't hit the loop, but I'm very happy nonetheless.

Thanks!
Mike
