### ISSUE TITLE
error in upgrading zebrazoom to v1.31 with python 3.8 on Linux

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#18]
Hi Olivier,

I tried upgrading zebrazoom today on my Linux machine working on Linux-Mint, with python 3.8
my previous version worked perfectly and was: 1.30.22 

when I launched : 

> pip install zebrazoom --upgrade

I got an error:

ERROR: Could not find a version that satisfies the requirement PyQt6-Qt6>=6.2.3 (from PyQt6->zebrazoom) (from versions: none)
ERROR: No matching distribution found for PyQt6-Qt6>=6.2.3 (from PyQt6->zebrazoom)

I tried a different way forcing a different way to install PyQt6 using ([from this discussion](https://forum.qt.io/topic/126325/pyqt6-charts-doesn-t-macthing-any-distribuition/10)):

> pip3 install --index-url https://www.riverbankcomputing.com/pypi/simple/ --pre --upgrade PyQt6
> pip3 install --index-url https://www.riverbankcomputing.com/pypi/simple/ --pre --upgrade PyQt6-Charts

But none of these commands worked, I had the same error than when I try to upgrade zebrazoom.

I also tried running:

> pip install PySide6 --upgrade

Which went through, but when I tried again upgrading ZZ I had the same error.

Can you please help me figure out the issue ?

**Comment by oliviermirat** [comment]
Hi Mathilde,
Thank you for reporting this! We will fix it soon and will let you know.

**Comment by mathildelpx** [comment]
I thought it might be python versioning issue, so I tried to install it with python 3.7;

It got stuck, attached is the error message I got
[error_report.txt](https://github.com/oliviermirat/ZebraZoom/files/8079541/error_report.txt)

Related to this, I really think you should provide a specific environment to the users instead of asking user to create an empty environment and then asking the user to install zebrazoom inside, as a yml file.

**Comment by oliviermirat** [comment]
Ante is suggesting you type these three commands:

pip install pip --upgrade
pip install setuptools --upgrade
pip install zebrazoom --upgrade

If the first line doesn't work you could try instead: 
pip install pip --upgrade --user

Can you please try those three commands and see if it works?

**Comment by mathildelpx** [comment]
Succesfully upgraded pip and setuptools.

Got an error when upgrading ZZ:

Collecting PyQt6-sip<14,>=13.2
  Using cached PyQt6_sip-13.2.1-cp38-cp38-manylinux1_x86_64.whl (310 kB)
Collecting PyQt6
  Using cached PyQt6-6.2.2-cp36-abi3-manylinux1_x86_64.whl (7.7 MB)
  Using cached PyQt6-6.2.1-cp36-abi3-manylinux1_x86_64.whl (7.7 MB)
  Using cached PyQt6-6.2.0.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Querying qmake about your Qt installation...
      /home/mathilde.lapoix/anaconda3/envs/ZebraZoom/bin/qmake -query
      Traceback (most recent call last):
        File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-pqksw2el/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/tmp/pip-build-env-pqksw2el/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-pqksw2el/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 610, in setup
          self.update(tool)
        File "project.py", line 158, in update
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by oliviermirat** [comment]
Ok, sorry about this. We will investigate further.

**Comment by oliviermirat** [comment]
We decided to support both PyQt5 and PyQt6 to fix this issue. We are still working on a few small things (such as the size of fonts, etc...) but other than that everything should be working fine now.
