### ISSUE TITLE
config file saves temp parameters from buiding 

### ISSUE THREAD

**Issue by mcarbotano** [oliviermirat/ZebraZoom#2]
The program will remember the first and last frames used for the parameters selection and will save it in the final config file. If you then want to analyze any video only the frames included between the first and last frame parameters will be process. To analyze the whole video (or another video) you have to manually delete the first and last frame parameters from the config file.

Best

**Comment by oliviermirat** [comment]
During the creation of the config file, at one point you will get two windows, one called "Choose where the analysis of the video should start" and another called "Control". If you click on the button "I want the tracking to run on the entire video!", the config file created will not contain the "firstFrame" and "lastFrame" parameters.
