### ISSUE TITLE
zebrazoom stuck after background extraction when launched through command line

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#23]
Hi Olivier, 

### **Error:**
----------------------------------

Tracking gets stuck after background extraction when launched through command line.

**To reproduce:**
-----------------------------------

in conda env with zebrazoom installed, launch from terminal:
> python -m zebrazoom /network/lustre/iss01/wyart/rawdata/mathilde.lapoix/Behavior/220118 F3_run1 avi /home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/zebrazoom/configuration/config_ML.json

config used here: [config_ML.txt](https://github.com/oliviermirat/ZebraZoom/files/8115784/config_ML.txt)

was prompted in terminal:

> The data produced by ZebraZoom can be found in the folder: /home/mathilde.lapoix/anaconda3/envs/ZebraZoom/lib/python3.8/site-packages/zebrazoom/ZZoutput
> start get background
> Background Extracted

Before background extraction, was asked to click on tip of the tail and beginning of the tail succesfully. 

### **Expected behavior**
----------------------------------------------

Tracking is launched and I can follow the steps of the process through the terminal.

### **Environment**
--------------------------------------------------------------

zebrazoom: 1.32.2
plateform: Linux Mint 18.3 Sylvia - x86-64
python: 3.8.5

### **Additional info**
--------------------------------------------------------------

I have no problem in getting the tracking to run when I launch it from the GUI.

**Comment by oliviermirat** [comment]
Hi Mathilde,
I wonder if the tracking might actually be happening. Indeed the parameter "freqAlgoPosFollow" is automatically added to the configuration file when you launch the tracking through the GUI but not when you launch it through the command line. And here I don't see "freqAlgoPosFollow" in your config file, so it's normal that it is not printing the frames numbers when the tracking is launched through the command line. Could you please add the parameter:
"freqAlgoPosFollow" : 10
inside your configuration and try to launch it through the command line?

**Comment by mathildelpx** [comment]
Perfect Olivier, thanks a lot ! It was indeed the case.
