### ISSUE TITLE
Feature Request: Displaying full skeleton of the bout of the fish

### ISSUE THREAD

**Issue by GautamSridhar** [oliviermirat/ZebraZoom#25]
Hi Olivier,

For displaying the bout during visualization, an output like this would be quite neat - 

![image](https://user-images.githubusercontent.com/17831253/155366342-ca88e755-bbbd-433e-9c45-926b6eac2fee.png)

This is an example from the old phtaxis data that is processed so that it matches Joao's bout outputs from their tracking.

It might be easier to perform bout classification using unsupervised clustering once you have such an output as well.

I can send you the code for the processing once you're ready to work on this part. Let me know.

Regards,

**Comment by oliviermirat** [comment]
Hi Gautam,

Thank you, I will let you know when I'm ready to integrate this.

**Comment by oliviermirat** [comment]
This has been implemented for the bouts visualization now. I will integrate it in the bouts clustering later on.
