### ISSUE TITLE
GUI: "View bout video" the video field of view changes from frame to frame

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#3]
Hi !

Using last pip version of the software; zebrazoom-0.6.
And working on Ubuntu version #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017

When I look at ZZ output using the GUI and click on the button "View bout video", I get the window with the video tracked, but the field of view changes from frames to frames. It makes it very difficult to follow the tail and check the tracking.
Attached are examples of the different field of view I get for the same bout, different frames.

Could you make the field of view constant ?

Thanks !

**Comment by oliviermirat** [comment]
Hello,
You can click instead on "View video for Well _numWell_" and it should work (this will also start reading the video from the beginning of the bout).
But thanks for the feedback, I should indeed make this better in the future as it is a little confusing at the moment.
