### ISSUE TITLE
"Open experiment organization excel files folder" button in the GUI doesn't work

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#4]
Hi Olivier,

Working on Linux, I tried to explore the function "Analyse ZZ output" and when I tried to choose in which folder to save the excel file, I couldn't as clicking on the button doesn't work.

Maybe it's a linux issue ? the function to make a folder window to pop up works anyway, I can open the ZZ output folder / config folder for example.

Thanks for your answer

**Comment by mathildelpx** [comment]
* I mean it doesn't do anything when I click on the button. The GUI doesn't crash though.

**Comment by oliviermirat** [comment]
Hi Mathilde,
Thanks for the feedback, it does look like it's working on Windows but not on Linux. I will investigate and I will let you know asap.

**Comment by mathildelpx** [comment]
Hi Olivier, 

Thanks for fixing this issue in the new version.
