### ISSUE TITLE
Analyse ZZ output only takes example.xls as excel file, not the one I chose

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#5]
Hi Olivier,

I'm trying to analyse ZZ output using the GUI. 
I created a experiment organisation excel file (picture attached). I selected it via the GUI. I tried either "Compare populations with kinematic parameters" and "Cluster bouts of movements", and I got the same results: the analysis is made on the example excel file. (I know it since the folder "resultsKinematic/example" was created at the exact moment I launched the analysis and not before, and also the parameters analysed in the kinematics analysis are the one I chose). 

Probably there's a default excel file that is not being updated by user input ? I couldn't find where it is processed in the code. 

Let me know what you think.

**Comment by mathildelpx** [comment]
/home/mathilde.lapoix/Bureau/Capture du 2020-10-05 15-54-05.png

**Comment by oliviermirat** [comment]
Hi Mathilde,
Thanks a lot for the feedback!
Indeed it was always taking the default excel file.
If you update zebrazoom to the latest version (0.21) with "pip install zebrazoom --upgrade" it should work now.

**Comment by oliviermirat** [comment]
Salut Mathilde,

Est-ce que je peux fermer cet "issue" sur Github?

Tiens moi au courant stp,

Olivier

Le lun. 5 oct. 2020 à 15:59, mathildelpx <notifications@github.com> a
écrit :
