### ISSUE TITLE
Keep same tail extremity positions for all videos in a folder

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#6]
Hi!

Using ZZ version: 0.33

I would like to track multiple videos in one folder when selecting manually the tail extremity. Using the GUI, I know it is possible to do this for all videos prior to the tracking using "Run ZZ on multiple videos/ Manual first frame tail extremity".
However, my FOV and fish position don't change between videos and the tracking is very sensitive to the given tail position.
To be consistent across videos, I would like to use exact tail positions for all videos.

The only way I can do it right now is by copying the 2 csv files generated and rename them to match all videos.

Do you think you could implement something to allow this automatically ? Like an GUI option to check before doing the manual detection ?

Thanks a lot !

**Comment by oliviermirat** [comment]
Hi,

Yes, you can now use this script: https://github.com/oliviermirat/ZebraZoom/blob/master/otherScripts/duplicateHeadTailTipPositions.sh
