### ISSUE TITLE
Error in ZZ version 1.32.45

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#62]
Hey Olivier,

I  get this error as soon as mouse is moved with the latest version of ZZ:

Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\GUI_InitialClasses.py", line 238, in mouseMoveEvent
flowchartPos = self._flowchart.mapFromGlobal(evt.globalPos())
AttributeError: 'QMouseEvent' object has no attribute 'globalPos'

**Comment by oliviermirat** [comment]
Hi Maha,

Thanks a lot for the feedback. @anthepro : can you please check?

**Comment by oliviermirat** [comment]
@Maha314 : if you update to the latest version (1.32.46) it should be working now, please confirm if it's working or not.
