### ISSUE TITLE
Analyze ZZ output analysis step: file reference error

### ISSUE THREAD

**Issue by williamjoo** [oliviermirat/ZebraZoom#79]
The analyze output step (through the GUI) yields the following error, whether analyzing my own data or the provided example videos. The relevant directory '.../zebrazoom/dataAnalysis/resultsKinematic/' does not exist, and it seems not to be generated by the previous steps in the pipeline.

Traceback (most recent call last):
  File "C:\Users\joo0000\AppData\Local\Continuum\anaconda3\envs\zebrazoom\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUI.py", line 945, in <lambda>
    self._launchBtn.clicked.connect(lambda: self._populationComparison(self._tailTrackingParametersCheckbox.isChecked(), self._saveInMatlabFormatCheckbox.isChecked(), self._saveRawDataCheckbox.isChecked(), self._forcePandasRecreation.isChecked(), self._minNbBendForBoutDetect.text(), self._discardRadioButton.isChecked(), self._keepRadioButton.isChecked(), self._frameStepForDistanceCalculation.text()))
  File "C:\Users\joo0000\AppData\Local\Continuum\anaconda3\envs\zebrazoom\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUI.py", line 998, in _populationComparison
    populationComparaison(nameOfFile, resFolder, globParam, conditions, genotypes, os.path.join(paths.getDataAnalysisFolder(), 'resultsKinematic'), 0, True)
  File "C:\Users\joo0000\AppData\Local\Continuum\anaconda3\envs\zebrazoom\lib\site-packages\zebrazoom\dataAnalysis\dataanalysis\populationComparaison.py", line 15, in populationComparaison
    os.mkdir(outputFolderResult)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\joo0000\\AppData\\Local\\Continuum\\anaconda3\\envs\\zebrazoom\\Lib\\site-packages\\zebrazoom\\dataAnalysis\\resultsKinematic\\220801_test'

ZebraZoom version 1.32.84

**Comment by oliviermirat** [comment]
Thank you for the feedback. We've seen this error before actually. We will try to solve it soon, but in the meantime, there could be two options to fix this right away:

1 - the first option could be to simply manually create the missing sub-folders (such as the resultsKinematic sub-folder) inside the zebrazoom/dataAnalysis folder (the sub-folders you would create would be empty). You can see all the sub-folders that should be present in that folder here: https://github.com/oliviermirat/ZebraZoom/tree/master/zebrazoom/dataAnalysis

2 - the second option would be to reinstall the software by downloading this zip: https://github.com/oliviermirat/ZebraZoom/releases/latest/download/ZebraZoom-Windows.zip (then you need to double-click on ZebraZoom.exe inside the unzipped folder). That second option would require you to move your tracked data from one ZZoutput folder to another

Please let me know if one of these options solves the problem or not, I'd be happy to provide more help if needed.

**Comment by williamjoo** [comment]
Thank you for the advice. The first option allowed analysis step to proceed (manually created subfolders 'data', 'resultsKinematic', and 'resultsClustering' within zebrazoom/dataAnalysis).

**Comment by oliviermirat** [comment]
Ok, please feel free to let me know if you need any other advice.
