### ISSUE TITLE
freeze when launching ZZ on a video, need to close and relaunch GUI for it to run properly

### ISSUE THREAD

**Issue by mathildelpx** [oliviermirat/ZebraZoom#8]
Hi,

Using ZZ v=0.39

**What I'm trying to do:**

Run ZZ on a video.

**Expected behavior**

After choosing video and config file, clicked on "Launch ZZ", I expect a window to pop up to click on start and end of the tail.

**What happens**

- No window pops up.

- in the terminal, I get an error:
"QObject::moveToThread: Current thread (0x5607a922ef70) is not the object's thread (0x5607a27f7420).
Cannot move to target thread (0x5607a922ef70)"
BUT I always get this error even when ZZ can run normally.

What's really weird is that this only happens when I used the GUI for something else before. For example, I launched the GUI to visualize ZZ output. Then went back to start page, and tried to launch ZZ. 
This never happens when I directly go to launch ZZ after opening the GUI.

**Comment by oliviermirat** [comment]
Hello,
Thank you for the feedback. 
I think that the best way to solve this issue might be to migrate away from Tkinter (the library used to implement the GUI) to another GUI library, as Tkinter as proved itself to be buggy/impractical in many different situations. Hopefully we will be able to do this migration away from Tkinter in the not too distant future, but this will still take quite some work to do. 
I'm thus temporarily closing this issue, but I will reopen it in the future when we either migrate away from Tkinter or if I find another way of fixing this.
Best,
Olivier
