### ISSUE TITLE
tail angle smoothed.txt

### ISSUE THREAD

**Issue by xululu917** [oliviermirat/ZebraZoom#80]
hi!
it's very excellent work!
but i want to know how can i extract the data smoothed tail angle ?i can only extract the raw data of tail angle.

**Comment by oliviermirat** [comment]
Hello,
Thank you!
You should be able to extract it from the super structure, as explained here: https://zebrazoom.org/documentation/docs/behaviorAnalysis/ZZoutputAnalysisWithPython
Please let me know if this works for you or not (you can also contact me by email (info@zebrazoom.org) if you want to share more information such as configuration or results files)

**Comment by xululu917** [comment]
thank you ，i have solved it ！

**Comment by oliviermirat** [comment]
Ok, great!
