### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by srevisu** [oliviermirat/ZebraZoom#82]
Hi, thanks for creating and sharing ZebraZoom with us. 

When I was trying to open my .avi video files for the creation of a configuration file, I was given the following error:
![image](https://user-images.githubusercontent.com/116907456/198690434-9753a9ef-d5bd-49bc-aced-330223a648f3.png)
![image](https://user-images.githubusercontent.com/116907456/198690533-9524734d-c13a-4661-a0a2-1c65e01e021b.png)
Not sure if this is something you have seen before, would appreciate any guidance.

**Comment by oliviermirat** [comment]
Hello,
Thank you for your feedback!
I made a change in the code that I think might fix this issue: please upgrade ZebraZoom to its latest version (1.33.04) on your computer to get this bug fix. 
However, despite this potential bug fix, in your situation, you might need to further optimize the tracking parameters of your configuration file, either after running a test tracking:
![image](https://user-images.githubusercontent.com/17452771/198764696-23a71586-aadd-4566-b0d9-8009896a4cbe.png)
Or from the main menu of ZebraZoom:
![image](https://user-images.githubusercontent.com/17452771/198765268-78b3f225-90e3-4e2e-b4dd-72cdb9700d12.png)
Please do let me know if this fixes your issue, if it doesn't I would be happy to help you troubleshoot more.

**Comment by oliviermirat** [comment]
(the optimization of tracking parameters is only necessary if the tracking quality is not good enough without optimization)

**Comment by oliviermirat** [comment]
Hello,
Sorry, I'm just realizing now that I forgot to push the changes I mentioned in my previous message to the latest version of ZebraZoom (so actually I had not changed anything in the previous version...).
But I've pushed the changes now, so if you upgrade to the version 1.33.05, you should now get the changes and you can check if that works better.

**Comment by srevisu** [comment]
Got it, thanks for the update!
